version: "3.2"
services:
  katalon-agent:
    image: "katalonstudio/agent"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SERVER_URL: https://analytics.katalon.com
      KATALON_USERNAME: muhammad.alyafi@external.danone.com
      AGENT_NAME: my_docker_agent
      TEAM_ID: 891220
      KATALON_API_KEY: 939158ca-63ce-43a5-a954-479eced38bf6
    volumes:
      - katalon-runtime-engines:/root/.katalon

volumes:
  katalon-runtime-engines:
