<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_DAN-AP-T-ADF801-Spoke-IDN-Ingestion</name>
   <tag></tag>
   <elementGuidId>37cc5dde-d693-4547-8c0a-4d0546df0741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/app-datafactory-entry/div/div/app-select-datafactory/div/app-data-factory-select/app-dropdown[2]/app-dropdown-container/div/div[2]/div/div/div/div/div[2]/div/ul/cdk-virtual-scroll-viewport/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0caeb53f-f18c-4ec5-9656-1c2814a6a919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltipposition</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>2b8217c2-a936-4e67-8009-c7a437f9846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showdelay</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>4e2c3d01-78cc-4b23-82d6-d5a63e977fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hidedelay</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>5d780951-2c36-44b0-83bf-41d4ea62cd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>744cd321-346d-4e95-91a8-be2cba684031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ab8388d7-69b9-4825-9de1-d97212aba1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-element selection-option</value>
      <webElementGuid>1c59497a-ba47-44c6-bab7-287d724077af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>DAN-AP-T-ADF801-Spoke-IDN-Ingestion</value>
      <webElementGuid>af48c823-8730-436f-9181-decfc4151af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAN-AP-T-ADF801-Spoke-IDN-Ingestion</value>
      <webElementGuid>72e79c2f-a0ec-46a1-bdbc-4c492c888818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-datafactory-entry[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;entry-container&quot;]/div[@class=&quot;background-image&quot;]/app-select-datafactory[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;new-entry-container ng-star-inserted&quot;]/app-data-factory-select[@class=&quot;ng-star-inserted&quot;]/app-dropdown[@class=&quot;datafactory-select&quot;]/app-dropdown-container[1]/div[@class=&quot;vertical-container fix-asterisk-style option-open&quot;]/div[@class=&quot;input-vertical-container&quot;]/div[@class=&quot;input-vertical-above&quot;]/div[@class=&quot;input-wrapper-with-error&quot;]/div[@class=&quot;input-wrapper-inner&quot;]/div[@class=&quot;select-main ng-star-inserted option-open input-vertical-select&quot;]/div[@class=&quot;option-container&quot;]/div[@class=&quot;ng-star-inserted&quot;]/ul[@class=&quot;dropdown-items&quot;]/cdk-virtual-scroll-viewport[@class=&quot;cdk-virtual-scroll-viewport dropdown-viewport cdk-virtual-scroll-orientation-vertical ng-star-inserted&quot;]/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/div[@class=&quot;dropDownItem dropdown-item ng-star-inserted&quot;]/div[@class=&quot;p-element selection-option&quot;]</value>
      <webElementGuid>d528b76d-6d4b-4ce0-85bd-998892189473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/app-datafactory-entry/div/div/app-select-datafactory/div/app-data-factory-select/app-dropdown[2]/app-dropdown-container/div/div[2]/div/div/div/div/div[2]/div/ul/cdk-virtual-scroll-viewport/div/div[3]/div</value>
      <webElementGuid>567cc3eb-1027-4b56-ad41-60a2496a0e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[16]</value>
      <webElementGuid>74704650-85a2-466d-8ea3-094188e77828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::div[16]</value>
      <webElementGuid>310a6cb8-db46-4979-8cd7-1a1bb9a0b339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::div[2]</value>
      <webElementGuid>1ea0e255-0eae-4a57-a18b-6e0e9e0b9aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[8]</value>
      <webElementGuid>1852df0b-7e22-4727-b462-d54ccd9a1289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>7a7a4526-114d-4c63-87b9-ddec3ef80768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DAN-AP-T-ADF801-Spoke-IDN-Ingestion' or . = 'DAN-AP-T-ADF801-Spoke-IDN-Ingestion')]</value>
      <webElementGuid>ca58d8c7-f922-43ae-961e-fec5d1ab29e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
